version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - my-db1:/var/lib/postgres
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3008:${PORT}
    tty: true
    depends_on:
      - postgres
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app

volumes:
  my-db1:
  
