version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    # hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root
      MYSQL_DATABASE: sua_base_de_dados
      MYSQL_USER: seu_usuario
      MYSQL_PASSWORD: sua_senha
    volumes:
      - my-db1:/var/lib/mysql
      - ./grant_permissions.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    tty: true # Adicione esta linha para permitir um terminal interativo
    depends_on:
      - mysql
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app

volumes:
  my-db1:
  
